// Secrets set via `wrangler secret put` (and mirrored in `.dev.vars` for
// local dev) aren't visible to `wrangler types` unless `.dev.vars` happens to
// exist at generation time, so `worker-configuration.d.ts` (gitignored,
// regenerated by `pnpm typecheck` / `pnpm dev`) can't be relied on alone to
// type them. Declaration-merge them onto `Cloudflare.Env` here instead, so
// `import { env } from 'cloudflare:workers'` is correctly typed regardless
// of whether `.dev.vars` is present when types are (re)generated.
declare namespace Cloudflare {
  interface Env {
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    SESSION_SECRET: string;
  }
}
